version: '3'

services:
  web:
    build: .
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/db
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres # Don't use this password in production
      - POSTGRES_DB=db
    expose:
      - 5432